package com.los.core.creditintelligence.cutover.domain;

public enum ComparisonClass {
    EXACT_MATCH,
    NON_MATERIAL_DIFFERENCE,
    MATERIAL_POLICY_DIFFERENCE,
    MATERIAL_AMOUNT_DIFFERENCE,
    MATERIAL_PRICING_DIFFERENCE,
    CANONICAL_REFER,
    CANONICAL_DATA_INSUFFICIENT,
    LEGACY_DEFAULT_DEPENDENT,
    CANONICAL_MORE_PERMISSIVE,
    CANONICAL_STRICTER
}
