package com.los.core.creditintelligence.banking.domain;

public enum BankingMismatchClassification {
    LEGACY_DEFAULT_USED,
    LEGACY_MANUAL_VALUE,
    CANONICAL_DATA_INSUFFICIENT,
    ACCOUNT_OWNERSHIP_MISMATCH,
    STATEMENT_INCOMPLETE,
    DUPLICATE_REMOVED,
    SELF_TRANSFER_EXCLUDED,
    LOAN_DISBURSEMENT_EXCLUDED,
    CAPITAL_INFUSION_EXCLUDED,
    TRANSACTION_CLASSIFICATION_DIFFERENCE,
    EMI_DETECTION_DIFFERENCE,
    BALANCE_CALCULATION_DIFFERENCE,
    OD_LIMIT_MISSING,
    OTHER
}
