package com.los.core.creditintelligence.reconciliation.domain;

/**
 * Structured explanation codes for reconciliation results (RECON_EXPLANATION_V1).
 */
public enum ExplanationCode {
    PERIOD_MISMATCH,
    PARTIAL_GST,
    PARTIAL_BANK_STATEMENT,
    PRESUMPTIVE_ITR,
    CREDIT_SALES_TIMING,
    RECEIVABLE_COLLECTION_LAG,
    ADVANCE_CUSTOMER_RECEIPTS,
    NON_OPERATING_BANK_CREDITS,
    SELF_TRANSFERS_EXCLUDED,
    LOAN_DISBURSEMENTS_EXCLUDED,
    CAPITAL_INFUSIONS_EXCLUDED,
    CASH_SALES_NOT_BANKED,
    MULTI_GSTIN_AGGREGATION,
    REVISED_ITR,
    GST_RETURN_DELAY,
    BUREAU_REPORT_STALE,
    BANK_EMI_NOT_DETECTED,
    BUREAU_EMI_MISSING,
    UNKNOWN_LENDER_MATCH,
    SOURCE_LOW_CONFIDENCE,
    MISSING_LEFT_OPERAND,
    MISSING_RIGHT_OPERAND,
    SUBJECT_MISMATCH,
    VALUES_ALIGNED,
    WITHIN_WARNING_TOLERANCE,
    MATERIAL_DIFFERENCE,
    CONFLICTING_SOURCES,
    LEGACY_METRIC_WRAP
}
