-- P0.1: seed policy-studio metric definitions (executable definitions registered; computation in Java services)

INSERT INTO ci_metric_definition (metric_code, version, description, domain, status, definition_json)
VALUES
('banking.qr_settlement.amount_total_3m', 'V1', 'QR settlement amount total 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"INR","missingIfUnclassified":true}'::jsonb),
('banking.qr_settlement.average_daily_3m', 'V1', 'QR settlement average daily 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"INR","missingIfUnclassified":true}'::jsonb),
('banking.qr_settlement.count_3m', 'V1', 'QR settlement count 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"COUNT","missingIfUnclassified":true}'::jsonb),
('banking.qr_settlement.average_monthly_count_3m', 'V1', 'QR settlement avg monthly count 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"COUNT","missingIfUnclassified":true}'::jsonb),
('banking.transaction_count_3m', 'V1', 'Transaction count 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"COUNT"}'::jsonb),
('banking.average_monthly_transaction_count_3m', 'V1', 'Avg monthly transaction count 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"COUNT"}'::jsonb),
('banking.inward_cheque_return_count_3m', 'V1', 'Inward cheque return count 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"COUNT"}'::jsonb),
('banking.inward_cheque_return_ratio_3m', 'V1', 'Inward cheque return ratio 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"PERCENT"}'::jsonb),
('BANK_POLICY_ADJUSTED_ADB_3M', 'V1', 'Tenant/product-scoped adjusted ADB 3m', 'BANKING', 'ACTIVE',
 '{"period":"TRAILING_3M","unit":"INR","scoped":true,"doNotMutateGlobal":"banking.avg_daily_balance_3m"}'::jsonb),
('bureau.max_dpd_6m', 'V1', 'Max DPD in last 6 months', 'BUREAU', 'ACTIVE',
 '{"period":"TRAILING_6M","unit":"DAYS"}'::jsonb),
('bureau.inquiries.current_month_count', 'V1', 'Bureau inquiries in current calendar month', 'BUREAU', 'ACTIVE',
 '{"period":"CALENDAR_MONTH","unit":"COUNT","clock":"EvaluationContext"}'::jsonb),
('bureau.consumer.score', 'V1', 'Consumer bureau score', 'BUREAU', 'ACTIVE',
 '{"unit":"SCORE"}'::jsonb),
('bureau.consumer.ntc', 'V1', 'No trade / thin file flag', 'BUREAU', 'ACTIVE',
 '{"unit":"BOOLEAN"}'::jsonb),
('bureau.accounts.credit_card_overdue_max', 'V1', 'Max CC overdue amount', 'BUREAU', 'ACTIVE',
 '{"unit":"INR"}'::jsonb),
('bureau.overdue.age_months', 'V1', 'Months since overdue reporting date', 'BUREAU', 'ACTIVE',
 '{"unit":"MONTHS"}'::jsonb),
('bureau.credit_after_overdue.exists', 'V1', 'New credit opened after overdue date', 'BUREAU', 'ACTIVE',
 '{"unit":"BOOLEAN"}'::jsonb),
('bureau.credit_after_overdue.clean_history_months', 'V1', 'Clean history months on post-overdue credit', 'BUREAU', 'ACTIVE',
 '{"unit":"MONTHS","requiresCleanDefinition":true}'::jsonb),
('bureau.accounts.writeoff_non_cc_count', 'V1', 'Non-CC write-off count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.cc_writeoff_count', 'V1', 'CC write-off count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.overdue_non_cc_count', 'V1', 'Non-CC overdue account count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.settled_count', 'V1', 'Settled account count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.restructured_count', 'V1', 'Restructured account count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.legal_suit_count', 'V1', 'Legal suit account count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.dbt_count', 'V1', 'DBT status count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.pwos_count', 'V1', 'PWOS status count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.lss_count', 'V1', 'LSS status count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.identity.pan_count', 'V1', 'Distinct PAN count on report', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb),
('bureau.accounts.account_sold_count', 'V1', 'Account sold count', 'BUREAU', 'ACTIVE', '{"unit":"COUNT"}'::jsonb)
ON CONFLICT (metric_code, version) DO NOTHING;
