package com.los.core.creditintelligence.policystudio.domain;

public enum AmbiguityType {
    MULTIPLE_CANONICAL_MATCHES,
    UNKNOWN_BUSINESS_TERM,
    MISSING_METRIC,
    UNCLEAR_PERIOD,
    UNCLEAR_DENOMINATOR,
    UNCLEAR_SCOPE,
    UNCLEAR_OPERATOR,
    BOUNDARY_AMBIGUITY,
    UNCLEAR_OUTCOME,
    CONFLICTING_RULE,
    MISSING_EXCEPTION_BEHAVIOUR,
    UNSUPPORTED_DATA
}
