package com.billiontech.bankstatement.model.enums;

public enum RedFlagType {
    HIGH_BOUNCE_RATE,
    CIRCULAR_TRANSACTIONS,
    CASH_DEPOSIT_SPIKE,
    HIGH_CASH_WITHDRAWAL,
    MINIMUM_BALANCE_BREACH,
    SUDDEN_LARGE_CREDIT,
    MULTIPLE_SALARY_SOURCES,
    ROUND_AMOUNT_DEPOSITS,
    END_OF_MONTH_INFLATION,
    DORMANT_PERIOD,
    PENAL_CHARGES,
    HIGH_OVERDRAFT_UTILIZATION,
    IRREGULAR_INCOME,
    DECLINING_BALANCE_TREND,
    HIGH_FOIR,
    FREQUENT_REVERSALS,
    LOW_CREDIT_DEBIT_RATIO,
    UNUSUAL_TRANSACTION_PATTERN,
    SALARY_DISCONTINUITY,
    EMI_IRREGULARITY
}
