package com.los.core.creditintelligence.gst.domain;

public enum GstMismatchClassification {
    LEGACY_DEFAULT_USED,
    LEGACY_MANUAL_VALUE,
    CANONICAL_DATA_INSUFFICIENT,
    CANONICAL_TURNOVER_DIFFERENT,
    MISSING_PERIODS,
    GSTR1_GSTR3B_VARIANCE,
    INACTIVE_GSTIN,
    MULTI_GSTIN_AGGREGATION_DIFFERENCE,
    DUPLICATE_PERIOD_REMOVED,
    ANNUALIZATION_DIFFERENCE,
    PARSER_DIFFERENCE,
    OTHER
}
