package com.los.core.creditintelligence.policystudio.runtime.canonicalconfig;

/**
 * Explicit canonical configuration failure codes. Absence of a pin is never
 * repaired by latest / current / active / product-default lookup.
 */
public enum CanonicalResolutionFailureCode {
    CUSTOMER_CATEGORY_NOT_PINNED,
    CUSTOMER_CATEGORY_NOT_FOUND,
    CUSTOMER_CATEGORY_VERSION_MISMATCH,
    WORKFLOW_VERSION_NOT_PINNED,
    WORKFLOW_VERSION_NOT_FOUND,
    WORKFLOW_VERSION_IDENTITY_MISMATCH,
    POLICY_APPLICABILITY_NOT_PINNED,
    POLICY_APPLICABILITY_NOT_FOUND,
    POLICY_APPLICABILITY_SCOPE_MISMATCH,
    POLICY_APPLICABILITY_DRIFT,
    POLICY_LIFECYCLE_NOT_ELIGIBLE,
    POLICY_DOCUMENT_NOT_PINNED,
    POLICY_DOCUMENT_NOT_FOUND,
    POLICY_DOCUMENT_IDENTITY_MISMATCH,
    SCORECARD_VERSION_NOT_RESOLVABLE,
    CALCULATION_DEFINITION_AMBIGUOUS,
    AUTHORED_CALCULATION_NOT_PINNED,
    BUREAU_REPORT_NOT_PINNED,
    BUREAU_REPORT_AMBIGUOUS,
    EVALUATION_AS_OF_NOT_RESOLVABLE
}
