-- Phase C3: banking fact definitions and metric definitions

INSERT INTO ci_fact_definition (canonical_path, version, description, value_type, domain, repeatable, sensitive, allowed_classifications, status)
VALUES
('banking.account.count', 1, 'Bank account count', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.account.current_count', 1, 'Current account count', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.account.od_cc_count', 1, 'OD/CC account count', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.statement.period_months', 1, 'Statement period months', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.statement.completeness_ratio', 1, 'Statement completeness ratio', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.statement.integrity_status', 1, 'Statement integrity status', 'STRING', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.average_3m', 1, 'Avg daily balance 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.average_6m', 1, 'Avg daily balance 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.average_12m', 1, 'Avg daily balance 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.minimum_3m', 1, 'Minimum balance 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.minimum_6m', 1, 'Minimum balance 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.minimum_12m', 1, 'Minimum balance 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.negative_days_3m', 1, 'Negative balance days 3m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.negative_days_6m', 1, 'Negative balance days 6m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.balance.negative_days_12m', 1, 'Negative balance days 12m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.total_3m', 1, 'Gross credits 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.total_6m', 1, 'Gross credits 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.total_12m', 1, 'Gross credits 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.average_monthly_3m', 1, 'Avg monthly credits 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.average_monthly_6m', 1, 'Avg monthly credits 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.average_monthly_12m', 1, 'Avg monthly credits 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.credit.adjusted_business_12m', 1, 'Adjusted business credits 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.debit.adjusted_business_12m', 1, 'Adjusted business debits 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.cash.deposit_3m', 1, 'Cash deposits 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.cash.deposit_6m', 1, 'Cash deposits 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.cash.deposit_12m', 1, 'Cash deposits 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.cash.deposit_ratio_12m', 1, 'Cash deposit ratio 12m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.bounce.cheque_count_3m', 1, 'Cheque returns 3m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.bounce.cheque_count_6m', 1, 'Cheque returns 6m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.bounce.nach_count_3m', 1, 'NACH returns 3m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.bounce.nach_count_6m', 1, 'NACH returns 6m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.obligation.emi_total_monthly', 1, 'Detected EMI total monthly', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.obligation.recurring_lender_debit_monthly', 1, 'Recurring lender debit monthly', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.obligation.lender_count', 1, 'Detected lender count', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.od_cc.average_utilisation_3m', 1, 'OD/CC avg utilisation 3m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.od_cc.average_utilisation_6m', 1, 'OD/CC avg utilisation 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.od_cc.peak_utilisation_6m', 1, 'OD/CC peak utilisation 6m', 'DECIMAL', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('banking.od_cc.days_above_90pct_6m', 1, 'OD/CC days above 90% 6m', 'INTEGER', 'BANKING', false, false, '["DERIVED"]'::jsonb, 'ACTIVE')
ON CONFLICT (canonical_path, version) DO NOTHING;

INSERT INTO ci_metric_definition (metric_code, version, description, domain, status, definition_json)
VALUES
('banking.avg_daily_balance_3m', 'V1', 'Average daily balance 3m (BANK_AVERAGE_DAILY_BALANCE_V1)', 'BANKING', 'ACTIVE',
 '{"method":"BANK_AVERAGE_DAILY_BALANCE_V1","months":3}'::jsonb),
('banking.avg_daily_balance_6m', 'V1', 'Average daily balance 6m', 'BANKING', 'ACTIVE',
 '{"method":"BANK_AVERAGE_DAILY_BALANCE_V1","months":6}'::jsonb),
('banking.avg_daily_balance_12m', 'V1', 'Average daily balance 12m', 'BANKING', 'ACTIVE',
 '{"method":"BANK_AVERAGE_DAILY_BALANCE_V1","months":12}'::jsonb),
('banking.adjusted_business_credits_3m', 'V1', 'Adjusted business credits 3m', 'BANKING', 'ACTIVE',
 '{"method":"ADJUSTED_BANKING_TURNOVER_V1","months":3}'::jsonb),
('banking.adjusted_business_credits_6m', 'V1', 'Adjusted business credits 6m', 'BANKING', 'ACTIVE',
 '{"method":"ADJUSTED_BANKING_TURNOVER_V1","months":6}'::jsonb),
('banking.adjusted_business_credits_12m', 'V1', 'Adjusted business credits 12m', 'BANKING', 'ACTIVE',
 '{"method":"ADJUSTED_BANKING_TURNOVER_V1","months":12}'::jsonb),
('banking.average_monthly_business_credits_6m', 'V1', 'Avg monthly adjusted credits 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.average_monthly_business_credits_12m', 'V1', 'Avg monthly adjusted credits 12m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.minimum_balance_3m', 'V1', 'Minimum end-of-day balance 3m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.negative_balance_days_6m', 'V1', 'Negative balance days 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.cash_deposit_ratio_12m', 'V1', 'Cash deposit / adjusted credits 12m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.cheque_return_count_3m', 'V1', 'Cheque return count 3m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.cheque_return_count_6m', 'V1', 'Cheque return count 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.nach_return_count_3m', 'V1', 'NACH return count 3m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.nach_return_count_6m', 'V1', 'NACH return count 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.monthly_obligation', 'V1', 'Detected monthly EMI obligation', 'BANKING', 'ACTIVE',
 '{"method":"BANK_EMI_DETECTION_V1"}'::jsonb),
('banking.od_cc_average_utilisation_6m', 'V1', 'OD/CC average utilisation 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.od_cc_peak_utilisation_6m', 'V1', 'OD/CC peak utilisation 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.od_cc_days_above_90pct_6m', 'V1', 'OD/CC days above 90% utilisation 6m', 'BANKING', 'ACTIVE', '{}'::jsonb),
('banking.statement_completeness', 'V1', 'Statement completeness ratio', 'BANKING', 'ACTIVE', '{}'::jsonb)
ON CONFLICT (metric_code, version) DO NOTHING;
