-- Phase C4: ITR/AIS/26AS fact and metric definitions

INSERT INTO ci_fact_definition (canonical_path, version, description, value_type, domain, repeatable, sensitive, allowed_classifications, status)
VALUES
('itr.return.available', 1, 'ITR return available', 'BOOLEAN', 'TAX', false, false, '["DERIVED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.return.latest_assessment_year', 1, 'Latest assessment year', 'STRING', 'TAX', false, false, '["VERIFIED","EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.return.latest_financial_year', 1, 'Latest financial year', 'STRING', 'TAX', false, false, '["VERIFIED","EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.return.form', 1, 'ITR form', 'STRING', 'TAX', false, false, '["VERIFIED","EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.return.filing_date', 1, 'ITR filing date', 'DATE', 'TAX', false, false, '["VERIFIED","EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.return.filing_status', 1, 'ITR filing status', 'STRING', 'TAX', false, false, '["DERIVED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.return.revised_flag', 1, 'Revised return flag', 'BOOLEAN', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.return.age_days', 1, 'Days since filing', 'INTEGER', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.income.salary', 1, 'Salary income', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.income.business_profession', 1, 'Business/profession income', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.income.capital_gains', 1, 'Capital gains', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.income.other_sources', 1, 'Other sources income', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.income.gross_total', 1, 'Gross total income', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED","DERIVED"]'::jsonb, 'ACTIVE'),
('itr.income.total', 1, 'Total income', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","VERIFIED","DERIVED"]'::jsonb, 'ACTIVE'),
('itr.business.gross_receipts', 1, 'Business gross receipts', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.business.turnover', 1, 'Business turnover', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","VERIFIED","DERIVED"]'::jsonb, 'ACTIVE'),
('itr.business.gross_profit', 1, 'Gross profit', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.business.ebitda', 1, 'EBITDA', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('itr.business.pbt', 1, 'Profit before tax', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.business.pat', 1, 'Profit after tax', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.balance.inventory', 1, 'Inventory', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.balance.receivables', 1, 'Trade receivables', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.balance.cash_bank', 1, 'Cash and bank', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.balance.total_assets', 1, 'Total assets', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.balance.payables', 1, 'Trade payables', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.balance.total_borrowings', 1, 'Total borrowings', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('itr.balance.net_worth', 1, 'Net worth', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","VERIFIED"]'::jsonb, 'ACTIVE'),
('itr.tax.tax_liability', 1, 'Tax liability', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.tax_paid', 1, 'Tax paid', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.tds', 1, 'TDS', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.tcs', 1, 'TCS', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.advance_tax', 1, 'Advance tax', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.self_assessment_tax', 1, 'Self assessment tax', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.refund', 1, 'Refund', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.tax.outstanding_demand', 1, 'Outstanding tax demand', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.presumptive.applicable', 1, 'Presumptive taxation applicable', 'BOOLEAN', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.presumptive.section', 1, 'Presumptive section', 'STRING', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.presumptive.gross_receipts', 1, 'Presumptive gross receipts', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.presumptive.declared_income', 1, 'Declared presumptive income', 'DECIMAL', 'TAX', false, false, '["EXTRACTED"]'::jsonb, 'ACTIVE'),
('itr.presumptive.margin', 1, 'Presumptive margin', 'DECIMAL', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.compliance.return_count_3y', 1, 'Returns filed in 3 years', 'INTEGER', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.compliance.late_filing_count_3y', 1, 'Late filings in 3 years', 'INTEGER', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('itr.compliance.revised_return_count_3y', 1, 'Revised returns in 3 years', 'INTEGER', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('ais.available', 1, 'AIS available', 'BOOLEAN', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('ais.reported_income_total', 1, 'AIS reported income total', 'DECIMAL', 'TAX', false, true, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('ais.interest_total', 1, 'AIS interest total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('ais.dividend_total', 1, 'AIS dividend total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('ais.business_receipt_total', 1, 'AIS business receipt total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('ais.cash_deposit_total', 1, 'AIS cash deposit total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('form26as.available', 1, 'Form 26AS available', 'BOOLEAN', 'TAX', false, false, '["DERIVED"]'::jsonb, 'ACTIVE'),
('form26as.tds_total', 1, '26AS TDS total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('form26as.tcs_total', 1, '26AS TCS total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('form26as.advance_tax_total', 1, '26AS advance tax total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE'),
('form26as.self_assessment_tax_total', 1, '26AS SAT total', 'DECIMAL', 'TAX', false, false, '["EXTRACTED","DERIVED"]'::jsonb, 'ACTIVE')
ON CONFLICT (canonical_path, version) DO NOTHING;

INSERT INTO ci_metric_definition (metric_code, version, description, domain, status, definition_json)
VALUES
('itr.business.turnover.latest_fy', 'V1', 'Business turnover latest FY', 'TAX', 'ACTIVE',
 '{"preferField":"sales_turnover","fallback":"gross_receipts|totalRevenue","selection":"ITR_EFFECTIVE_RETURN_SELECTION_V1"}'::jsonb),
('itr.business.turnover.previous_fy', 'V1', 'Business turnover previous FY', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.business.turnover.cagr_2y', 'V1', 'Business turnover CAGR 2Y', 'TAX', 'ACTIVE', '{"minYears":2}'::jsonb),
('itr.business.turnover.cagr_3y', 'V1', 'Business turnover CAGR 3Y', 'TAX', 'ACTIVE', '{"minYears":3}'::jsonb),
('itr.total_income.latest_fy', 'V1', 'Total income latest FY', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.business_income.latest_fy', 'V1', 'Business income latest FY', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.average_total_income_2y', 'V1', 'Average total income 2Y', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.average_total_income_3y', 'V1', 'Average total income 3Y', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.income_growth_yoy', 'V1', 'Income YoY growth', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.ebitda_margin', 'V1', 'EBITDA / turnover', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.pat_margin', 'V1', 'PAT / turnover', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.net_profit_growth', 'V1', 'PAT YoY growth', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.debt_equity', 'V1', 'Debt / equity', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.tol_tnw', 'V1', 'TOL / TNW', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.effective_tax_rate', 'V1', 'Tax / total income', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.tax_paid_to_income', 'V1', 'Tax paid / total income', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.tds_to_income', 'V1', 'TDS / total income', 'TAX', 'ACTIVE', '{}'::jsonb),
('itr.filing_timeliness', 'V1', 'Filing timeliness score', 'TAX', 'ACTIVE', '{"freshness":"ITR_FRESHNESS_POLICY_V1"}'::jsonb),
('itr.return_consistency_score', 'V1', 'Return consistency score', 'TAX', 'ACTIVE', '{}'::jsonb),
('xsrc.itr_26as_tds_variance', 'V1', 'ITR TDS vs 26AS TDS', 'TAX', 'ACTIVE', '{}'::jsonb),
('xsrc.itr_ais_income_variance', 'V1', 'ITR income vs AIS reported', 'TAX', 'ACTIVE', '{}'::jsonb)
ON CONFLICT (metric_code, version) DO NOTHING;
